import assert from "node:assert/strict";
import test from "node:test";

const bom = await import("../app/bom.ts");
const report = await import("../app/html-report.ts");
const model = await import("../app/model.ts");

const PIXEL =
  "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAA";
const SAFE_SVG = `<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE svg PUBLIC "-//W3C//DTD SVG 1.1//EN" "http://www.w3.org/Graphics/SVG/1.1/DTD/svg11.dtd">
<!-- Generated by graphviz -->
<svg width="120pt" height="60pt" viewBox="0.00 0.00 120.00 60.00" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" xml:space="preserve">
<g id="graph0" class="graph" transform="scale(1 1)">
<title>Harness &amp; diagram</title>
<polygon fill="white" stroke="transparent" points="0,0 120,0 120,60 0,60 0,0" />
<text text-anchor="middle" x="60" y="30" font-family="Times,serif" font-size="14.00">X1 &lt;safe&gt;</text>
<image xlink:href="${PIXEL}" width="1px" height="1px" preserveAspectRatio="xMidYMid meet" x="2" y="2" />
</g>
</svg>`;

function component(kind, id, designator) {
  const value = model.makeComponent(kind, 1, id);
  value.designator = designator;
  return value;
}

function realisticProject() {
  const project = model.createEmptyProject("Production <Harness> & Report");
  project.revision = 'B "release"';
  project.company = "Müller & Söhne";

  const x10 = component("connector", "x10", "X10");
  x10.name = "Remote connector";
  x10.pinCount = 1;

  const x2 = component("connector", "x2", "X2");
  x2.name = "Sensor connector";
  x2.pinCount = 2;
  x2.pinLabels = ["SENSE <HI>", "GND"];
  x2.manufacturer = "HARTING";
  x2.mpn = "HOUSING-2";
  x2.notes = "Mate before power\nInspect latch";
  x2.photo = {
    dataUrl: PIXEL,
    fileName: "x2.png",
    mimeType: "image/png",
    width: 1,
    height: 1,
    alt: 'X2 "sensor" connector',
  };

  const x1 = component("connector", "x1", "X1");
  x1.name = "Controller connector";
  x1.pinCount = 2;
  x1.pinLabels = ["+24V", "GND"];
  x1.manufacturer = "HARTING";
  x1.mpn = "HOUSING-1";

  const w1 = component("cable", "w1", "W1");
  w1.name = "Shielded sensor cable";
  w1.wireCount = 2;
  w1.wireLabels = ["RD", "BK"];
  w1.colors = ["RD", "BK"];
  w1.gauge = "22 AWG";
  w1.length = "2.5 m";
  w1.manufacturer = "LAPP";
  w1.mpn = "CABLE-1";
  w1.notes = "Route away from motor";

  project.components = [x10, x2, w1, x1];
  project.links = [
    {
      id: "x1-1",
      from: { nodeId: x1.id, portId: "pin:1", side: "right" },
      to: { nodeId: w1.id, portId: "wire:1", side: "left" },
      termination: {
        contact: { manufacturer: "HARTING", mpn: "CONTACT-A" },
        seal: { manufacturer: "HARTING", mpn: "SEAL-A" },
        stripLength: "5 mm",
        tooling: "Applicator A",
        notes: "Inspect crimp height",
      },
    },
    {
      id: "x1-2",
      from: { nodeId: x1.id, portId: "pin:2", side: "right" },
      to: { nodeId: w1.id, portId: "wire:2", side: "left" },
      termination: {
        contact: { manufacturer: "HARTING", mpn: "CONTACT-B" },
      },
    },
    {
      id: "x2-1",
      from: { nodeId: w1.id, portId: "wire:1", side: "right" },
      to: { nodeId: x2.id, portId: "pin:1", side: "left" },
      termination: {
        contact: { manufacturer: "HARTING", mpn: "CONTACT-A" },
        seal: { pn: "SEAL-B-INTERNAL" },
        stripLength: "4.5 mm",
        tooling: "Hand tool 42",
      },
    },
    {
      id: "x2-2",
      from: { nodeId: w1.id, portId: "wire:2", side: "right" },
      to: { nodeId: x2.id, portId: "pin:2", side: "left" },
    },
  ];
  return project;
}

test("report model maps metadata and naturally orders components", () => {
  const project = realisticProject();
  project.components.push(
    component("wire", "w10", "W10"),
    component("wire", "w2", "W2"),
  );
  const value = report.buildHarnessReportModel(project, SAFE_SVG);

  assert.deepEqual(value.project, {
    title: "Production <Harness> & Report",
    revision: 'B "release"',
    company: "Müller & Söhne",
    notes: "",
    schemaVersion: 3,
  });
  assert.deepEqual(
    value.connectors.map((item) => item.designator),
    ["X1", "X2", "X10"],
  );
  assert.deepEqual(
    value.cables.map((item) => item.designator),
    ["W1", "W2", "W10"],
  );
});

test("pinout maps signal, conductor, color, size, contact, and seal", () => {
  const value = report.buildHarnessReportModel(realisticProject(), SAFE_SVG);
  const x1 = value.connectors.find((item) => item.designator === "X1");
  assert.deepEqual(x1.pins[0], {
    pin: "1",
    label: "+24V",
    signal: "RD",
    cable: "W1",
    conductor: "1 · RD",
    color: "RD",
    gauge: "22 AWG",
    contactManufacturer: "HARTING",
    contactMpn: "CONTACT-A",
    sealPn: "SEAL-A",
  });
  assert.equal(x1.pins[1].contactMpn, "CONTACT-B");
  assert.equal(
    value.connectors.find((item) => item.designator === "X10").pins.length,
    1,
  );
});

test("termination rows map both ends and manufacturing metadata", () => {
  const value = report.buildHarnessReportModel(realisticProject(), SAFE_SVG);
  assert.equal(value.terminations.length, 3);
  assert.deepEqual(value.terminations[0], {
    connector: "X1",
    pin: "1",
    pinLabel: "+24V",
    cable: "W1",
    conductor: "1 · RD",
    signal: "RD",
    contactManufacturer: "HARTING",
    contactMpn: "CONTACT-A",
    sealPn: "SEAL-A",
    stripLength: "5 mm",
    tooling: "Applicator A",
    notes: "Inspect crimp height",
  });
  const opposite = value.terminations.find(
    (item) => item.connector === "X2" && item.pin === "1",
  );
  assert.equal(opposite.contactMpn, "CONTACT-A");
  assert.equal(opposite.sealPn, "SEAL-B-INTERNAL");
  assert.equal(opposite.stripLength, "4.5 mm");
  assert.equal(opposite.tooling, "Hand tool 42");
});

test("multiconductor cable appears once with modeled length and endpoints", () => {
  const value = report.buildHarnessReportModel(realisticProject(), SAFE_SVG);
  assert.deepEqual(value.cables, [
    {
      designator: "W1",
      kind: "cable",
      manufacturer: "LAPP",
      mpn: "CABLE-1",
      description: "Shielded sensor cable",
      length: "2.5 m",
      conductorCount: 2,
      gauge: "22 AWG",
      color: "",
      from: "X1:1, X1:2",
      to: "X2:1, X2:2",
      notes: "Route away from motor",
      twistedPair: "",
      additionalComponents: [],
      approvedAlternatives: [],
    },
  ]);
});

test("report BOM is the native builder output with mixed parts intact", () => {
  const project = realisticProject();
  const expected = bom.buildBomRows(project);
  const value = report.buildHarnessReportModel(project, SAFE_SVG);
  assert.deepEqual(value.bomRows, expected);
  assert.deepEqual(
    value.bomRows
      .filter((row) => row.category === "Crimp contact")
      .map(({ mpn, quantity }) => ({ mpn, quantity })),
    [
      { mpn: "CONTACT-A", quantity: 2 },
      { mpn: "CONTACT-B", quantity: 1 },
    ],
  );
  assert.equal(value.bomRows.find((row) => row.mpn === "SEAL-A").quantity, 1);
});

test("legacy projects without termination metadata export correctly", () => {
  const connector = component("connector", "legacy-x1", "X1");
  const cable = component("wire", "legacy-w1", "W1");
  const legacy = model.normalizeProject({
    schemaVersion: 2,
    title: "Legacy harness",
    components: [connector, cable],
    links: [
      {
        id: "legacy-link",
        from: { nodeId: connector.id, portId: "pin:1", side: "right" },
        to: { nodeId: cable.id, portId: "wire:1", side: "left" },
      },
    ],
  }).project;
  const value = report.buildHarnessReportModel(legacy, SAFE_SVG);
  assert.deepEqual(value.terminations, []);
  assert.match(
    report.renderHarnessReportHtml(value),
    /No explicit termination metadata is assigned\./,
  );
});

test("HTML escapes malicious text and preserves multiline notes", () => {
  const project = realisticProject();
  project.title = '<script>alert("title")</script> & test';
  project.notes = "Assembly & release\n\n<script>alert('notes')</script>\n- Keep <clear>";
  project.components[0].notes = "Line one\nLine <two> & 'three'";
  const html = report.renderHarnessReportHtml(
    report.buildHarnessReportModel(project, SAFE_SVG),
  );
  assert.doesNotMatch(html, /<script>alert/);
  assert.match(
    html,
    /&lt;script&gt;alert\(&quot;title&quot;\)&lt;\/script&gt; &amp; test/,
  );
  assert.match(html, /SENSE &lt;HI&gt;/);
  assert.match(html, /Line one\nLine &lt;two&gt; &amp; &#39;three&#39;/);
  assert.match(
    html,
    /Assembly &amp; release\n\n&lt;script&gt;alert\(&#39;notes&#39;\)&lt;\/script&gt;\n- Keep &lt;clear&gt;/,
  );
  assert.match(html, /B &quot;release&quot;/);
});

test("blank harness notes omit the report section and navigation link", () => {
  const project = realisticProject();
  project.notes = " \n\n ";
  const html = report.renderHarnessReportHtml(
    report.buildHarnessReportModel(project, SAFE_SVG),
  );
  assert.doesNotMatch(html, /id="notes"/);
  assert.doesNotMatch(html, /href="#notes"/);
});

test("embedded images remain while blob and external images are omitted", () => {
  const project = realisticProject();
  project.components.find((item) => item.designator === "X1").photo = {
    dataUrl: "blob:http://localhost/unsafe",
    fileName: "bad.png",
    mimeType: "image/png",
    width: 10,
    height: 10,
    alt: "unsafe",
  };
  project.components.find((item) => item.designator === "X10").photo = {
    dataUrl: "https://example.com/connector.png",
    fileName: "external.png",
    mimeType: "image/png",
    width: 10,
    height: 10,
    alt: "external",
  };
  const html = report.renderHarnessReportHtml(
    report.buildHarnessReportModel(project, SAFE_SVG),
  );
  assert.ok(html.includes(PIXEL));
  assert.doesNotMatch(html, /blob:/);
  assert.doesNotMatch(html, /https:\/\/example\.com/);
});

test("SVG sanitizer embeds Graphviz SVG and normalizes image href", () => {
  const sanitized = report.sanitizeDiagramSvg(SAFE_SVG);
  assert.ok(sanitized.startsWith("<svg"));
  assert.match(sanitized, /<svg[^>]*viewBox=/);
  assert.match(sanitized, /<image href="data:image\/png;base64,/);
  assert.match(sanitized, /Harness &amp; diagram/);
  assert.match(sanitized, /X1 &lt;safe&gt;/);
  assert.doesNotMatch(sanitized, /DOCTYPE|<\?xml|xlink:href/);
  const html = report.renderHarnessReportHtml(
    report.buildHarnessReportModel(realisticProject(), SAFE_SVG),
  );
  assert.match(html, /<div class="diagram"><svg/);
  assert.doesNotMatch(html, /src="[^"]+\.svg/);
});

test("SVG sanitizer rejects executable and external content", () => {
  const unsafe = [
    '<svg xmlns="http://www.w3.org/2000/svg"><script>alert(1)</script></svg>',
    '<svg xmlns="http://www.w3.org/2000/svg" onload="alert(1)"></svg>',
    '<svg xmlns="http://www.w3.org/2000/svg"><foreignObject>bad</foreignObject></svg>',
    '<svg xmlns="http://www.w3.org/2000/svg"><image href="javascript:alert(1)" /></svg>',
    '<svg xmlns="http://www.w3.org/2000/svg"><image href="https://example.com/a.png" /></svg>',
    '<svg xmlns="http://www.w3.org/2000/svg"><g style="background:url(x)"></g></svg>',
    '<svg xmlns="http://www.w3.org/2000/svg"><path fill="url(https://example.com/pattern.svg)" /></svg>',
  ];
  for (const svg of unsafe) {
    assert.throws(() => report.sanitizeDiagramSvg(svg));
  }
});

test("standalone HTML has report sections, CSP, and print CSS", () => {
  const project = realisticProject();
  project.notes = "Assembly notes\n\n- Keep TP1 away from power wiring.";
  const html = report.renderHarnessReportHtml(
    report.buildHarnessReportModel(project, SAFE_SVG),
  );
  assert.match(html, /^<!doctype html>/);
  assert.match(html, /<header>/);
  assert.match(html, /<main>/);
  assert.match(html, /id="connectors"/);
  assert.match(html, /id="terminations"/);
  assert.match(html, /id="bom"/);
  assert.match(html, /id="notes"/);
  assert.match(html, /CONTACT-A/);
  assert.match(html, /Assembly notes\n\n- Keep TP1 away from power wiring\./);
  assert.doesNotMatch(html, /id="validation"|Notes \/ Validation|validation warnings/i);
  assert.match(html, /default-src 'none'/);
  assert.match(html, /@media print/);
  assert.match(html, /thead\{display:table-header-group/);
  assert.doesNotMatch(html, /<script|<link|cdn/i);
});

test("HTML BOM renders shared quantities and natural designators", () => {
  const value = report.buildHarnessReportModel(realisticProject(), SAFE_SVG);
  const html = report.renderHarnessReportHtml(value);
  for (const row of value.bomRows) {
    assert.ok(html.includes(row.mpn || row.description));
    assert.ok(html.includes(`>${bom.formatBomQuantity(row.quantity)}<`));
  }
  assert.match(html, /X1:1, X2:1/);
});

test("repeated output and filenames are deterministic", () => {
  const project = realisticProject();
  const first = report.renderHarnessReportHtml(
    report.buildHarnessReportModel(project, SAFE_SVG),
  );
  const second = report.renderHarnessReportHtml(
    report.buildHarnessReportModel(project, SAFE_SVG),
  );
  assert.equal(first, second);
  assert.equal(
    report.htmlReportFilenameForTitle(" Amplifier Main Harness "),
    "amplifier-main-harness.html",
  );
  assert.equal(report.htmlReportFilenameForTitle(""), "wireform-harness.html");
});
